class MessagesController < ApplicationController
  # GET /messages or /messages.json
  def index: () -> untyped

  # GET /messages/1 or /messages/1.json
  def show: () -> nil

  # GET /messages/new
  def new: () -> untyped

  # GET /messages/1/edit
  def edit: () -> nil

  # POST /messages or /messages.json
  def create: () -> untyped

  # PATCH/PUT /messages/1 or /messages/1.json
  def update: () -> untyped

  # DELETE /messages/1 or /messages/1.json
  def destroy: () -> untyped

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_message: () -> untyped

  # Only allow a list of trusted parameters through.
  def message_params: () -> untyped
end
